- include_role:
    name: prometheus.prometheus.prometheus
  vars:
    prometheus_web_listen_address: "localhost:9090"
    prometheus_web_external_url: "/prometheus"
    ansible_fqdn: "csos.josefkolar.cz"
    prometheus_scrape_configs:
      - job_name: node
        static_configs:
          - targets: [localhost:9100]
      - job_name: mediamtx
        static_configs:
          - targets: [localhost:9998]
      - job_name: caddy
        static_configs:
          - targets: [localhost:2019]

- include_role:
    name: grafana.grafana.grafana
  vars:
    grafana_ini:
      paths:
        logs: "/var/log/grafana"
        data: "/var/lib/grafana"
      auth:
        ldap: {enabled: false}
      database:
        type: sqlite3
        path: grafana.db
      server:
        http_addr: 127.0.0.1
        http_port: 3000
        root_url: "https://csos.josefkolar.cz/grafana/"
      security:
        admin_user: admin
        admin_password: "{{ telemetry__grafana_admin_pass }}"

    grafana_ldap:
      servers: {}
      group_mappings: []
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090/prometheus/'
        basicAuth: false

    grafana_dashboards:
      - dashboard_id: 1860
        revision_id: 41
        datasource: prometheus

- include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_web_listen_address: "localhost:9100"
